// Generated by CoffeeScript 1.7.1
(function() {
  App.register("{{id}}", function(params, scope, widgets) {
    var $container, load, loader, response;
    $container = null;
    response = scope.createResponse();
    loader = scope.createLoader(response);
    load = function(url) {
      return loader.pull(url || params["url"]);
    };
    response.bindLoad(function() {
      if ($container) {
        $container.remove();
      }
      $container = $("<div />");
      $container.html(this.getContent());
      return $container.appendTo('body:first');
    });
    response.bindContext(function() {
      var context;
      context = this.getContext();
      if (context && context.onApply) {
        return context.onApply(function() {
          return response.apply();
        });
      } else {
        return response.apply();
      }
    });
    return {
      onApply: function(callback) {
        return response.bindApply(callback);
      },
      load: function(url) {
        return load(url);
      }
    };
  });

}).call(this);

//# sourceMappingURL=loaderAction.map
